[project]
name = "northlight"
version = "0.0.2a"
authors = [
  { name="Josh", email="josh.m.flatt@gmail.com" },
]
dependencies = [
    "datetime",
    "hatchling",
    "logging",
    "pandas",
    "paramiko",
    "python-dotenv",
    "uopy",
]
description = "Commonly used tools throughout my Python projects"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/josh-flatt/northlight"
Issues = "https://github.com/josh-flatt/northlight/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"